# Generated by Django 5.1.1 on 2024-09-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=4)),
                ('underlying_price', models.FloatField()),
                ('strike_price', models.FloatField()),
                ('volatility', models.FloatField()),
                ('time_to_maturity', models.FloatField()),
                ('risk_free_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
